import { motion } from "framer-motion";
import {
  FileText,
  Zap,
  Wifi,
  ShieldCheck,
  MessageSquare,
  ArrowUpRight,
} from "lucide-react";

const features = [
  {
    icon: Zap,
    title: "AI Summaries via Ollama",
    desc: "Structured, multi-page summaries generated by LLaMA 3 running locally through Ollama. No API calls, no latency beyond your hardware.",
  },
  {
    icon: ArrowUpRight,
    title: "Click-to-Source",
    desc: "Every AI insight links back to its exact source page. Trace any claim directly to the paragraph it came from.",
  },
  {
    icon: Wifi,
    title: "Fully Offline AI",
    desc: "Powered by Ollama — works completely air-gapped. Pull a model once and the product runs forever without internet.",
  },
  {
    icon: ShieldCheck,
    title: "Privacy-first",
    desc: "Your documents never leave your machine. Not to a cloud, not to a server, not to anyone. Full data sovereignty.",
  },
  {
    icon: MessageSquare,
    title: "Chat with PDFs",
    desc: "Ask natural language questions about any document. Contextual answers with source references via a lightweight RAG pipeline.",
  },
  {
    icon: FileText,
    title: "pdf.js Text Extraction",
    desc: "Mozilla's pdf.js renders and extracts text from complex layouts — multi-column papers, academic documents, and dense reports.",
  },
];

const container = {
  hidden: {},
  show: { transition: { staggerChildren: 0.08 } },
};

const item = {
  hidden: { opacity: 0, y: 24 },
  show: { opacity: 1, y: 0, transition: { duration: 0.55, ease: [0.22, 1, 0.36, 1] } },
};

export default function Features() {
  return (
    <section className="px-6 py-28">
      <div className="mx-auto max-w-6xl">
        {/* Section header */}
        <motion.div
          className="mb-16 text-center"
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.6 }}
        >
          <p className="mb-3 text-sm font-medium tracking-widest uppercase" style={{ color: "var(--accent-light)" }}>
            Capabilities
          </p>
          <h2 className="text-4xl font-bold tracking-tight sm:text-5xl">
            AI that works{" "}
            <span className="text-gradient">for you, locally</span>
          </h2>
          <p className="mt-4 text-lg" style={{ color: "var(--text-secondary)" }}>
            Every feature is designed around one principle: your data stays yours.
          </p>
        </motion.div>

        {/* Cards grid */}
        <motion.div
          className="grid gap-5 sm:grid-cols-2 lg:grid-cols-3"
          variants={container}
          initial="hidden"
          whileInView="show"
          viewport={{ once: true }}
        >
          {features.map(({ icon: Icon, title, desc }) => (
            <motion.div
              key={title}
              variants={item}
              className="card-hover group relative overflow-hidden rounded-2xl p-6"
              style={{
                background: "var(--surface)",
                border: "1px solid var(--border)",
              }}
            >
              {/* Hover glow */}
              <div
                className="pointer-events-none absolute inset-0 opacity-0 group-hover:opacity-100 transition-opacity duration-300 rounded-2xl"
                style={{
                  background: "radial-gradient(circle at 60% 10%, var(--glow) 0%, transparent 70%)",
                }}
              />

              {/* Icon */}
              <div
                className="mb-4 inline-flex h-11 w-11 items-center justify-center rounded-xl relative z-10"
                style={{
                  background: "linear-gradient(135deg, rgba(124,58,237,0.15), rgba(99,102,241,0.08))",
                  border: "1px solid var(--border)",
                }}
              >
                <Icon size={19} style={{ color: "var(--accent-light)" }} />
              </div>

              <h3 className="relative z-10 mb-2 font-semibold" style={{ color: "var(--text-primary)" }}>
                {title}
              </h3>
              <p className="relative z-10 text-sm leading-relaxed" style={{ color: "var(--text-secondary)" }}>
                {desc}
              </p>
            </motion.div>
          ))}
        </motion.div>
      </div>
    </section>
  );
}
